      - name: Clear npm cache
        run: npm cache clean --force
      - name: Install and build
        working-directory: frontend
        env:
          CI: "false"
          REACT_APP_BACKEND_URL: "https://sovereignquant.com.au"
          PUBLIC_URL: "."
        run: |
          npm install --legacy-peer-deps --no-optional
          npm run build
